
package View;

import Controller.Usuario;
import Model.Mongo;
import Controller.Validations;
import com.mongodb.DB;
import com.mongodb.MongoClient;
import com.mongodb.MongoException;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Font;
import javax.swing.JOptionPane;
import org.bson.Document;
import java.util.Date;
import java.text.SimpleDateFormat;




public class VenRegistro extends javax.swing.JFrame {
    //PARA INICIALIZAR LAS CLASE MONGO
     Mongo mongo;
    
    Usuario user = new Usuario("","","","","", 0);  
    
    
    public VenRegistro() {
        initComponents();
        // Crear una instancia de Mongo y pasar la instancia actual de VenRegistro
        mongo = new Mongo(this, null);
        txtTelefono.setText("09");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnom = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCi1 = new javax.swing.JTextField();
        JLOpVolver = new javax.swing.JLabel();
        JLVolver = new javax.swing.JLabel();
        JLOpRegistrar = new javax.swing.JLabel();
        JLRegistrar = new javax.swing.JLabel();
        txtcont = new javax.swing.JPasswordField();
        JlbNombreUsuario = new javax.swing.JLabel();
        JlbCorreo = new javax.swing.JLabel();
        JlbTelefono = new javax.swing.JLabel();
        JlbContraseña = new javax.swing.JLabel();
        Jlbedad = new javax.swing.JLabel();
        JlbCedula1 = new javax.swing.JLabel();
        JSedad = new javax.swing.JSpinner();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnom.setBackground(new java.awt.Color(227, 227, 227));
        txtnom.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtnom.setBorder(null);
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 140, 20));

        txtCorreo.setBackground(new java.awt.Color(227, 227, 227));
        txtCorreo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 140, 20));

        txtTelefono.setBackground(new java.awt.Color(227, 227, 227));
        txtTelefono.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, 20));

        txtCi1.setBackground(new java.awt.Color(227, 227, 227));
        txtCi1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtCi1.setBorder(null);
        getContentPane().add(txtCi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, 20));

        JLOpVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLOpVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLOpVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLOpVolverMouseExited(evt);
            }
        });
        getContentPane().add(JLOpVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        JLVolver.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLVolver.setForeground(new java.awt.Color(255, 255, 255));
        JLVolver.setText("VOLVER");
        JLVolver.setToolTipText("");
        getContentPane().add(JLVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, -1));

        JLOpRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLOpRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLOpRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLOpRegistrarMouseExited(evt);
            }
        });
        getContentPane().add(JLOpRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 130, 40));

        JLRegistrar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        JLRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        JLRegistrar.setText("Registrarse");
        getContentPane().add(JLRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 100, 40));

        txtcont.setBackground(new java.awt.Color(227, 227, 227));
        txtcont.setBorder(null);
        getContentPane().add(txtcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 130, 20));

        JlbNombreUsuario.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        JlbNombreUsuario.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JlbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, 10));

        JlbCorreo.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        JlbCorreo.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JlbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 10));

        JlbTelefono.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        JlbTelefono.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JlbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 200, 10));

        JlbContraseña.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        JlbContraseña.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JlbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 10));

        Jlbedad.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        Jlbedad.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(Jlbedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 190, 20));

        JlbCedula1.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        JlbCedula1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(JlbCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 210, 20));

        JSedad.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        JSedad.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(JSedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 100, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VenRegistro.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        txtnom.setBackground(new java.awt.Color(0, 0, 0, 0));       // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void JLOpVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpVolverMouseClicked
        VenSesion sesion = new VenSesion();
        sesion.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_JLOpVolverMouseClicked

    private void JLOpVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpVolverMouseEntered
        JLVolver.setFont(new Font("Calibri", Font.BOLD, 18));        // TODO add your handling code here:
    }//GEN-LAST:event_JLOpVolverMouseEntered

    private void JLOpVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpVolverMouseExited
        JLVolver.setFont(new Font("Calibri", Font.PLAIN, 18));        // TODO add your handling code here:
    }//GEN-LAST:event_JLOpVolverMouseExited

    private void JLOpRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpRegistrarMouseClicked
        JlbCorreo.setText("");
        JlbTelefono.setText("");
        JlbCedula1.setText("");
        JlbContraseña.setText("");
        Jlbedad.setText("");

    // Validaciones
    if(!Validations.validarContraseña(txtcont.getText())){
        JlbContraseña.setText("Error, permitido Letras, numeros para mas seguridad");
        return;
    }
    
    if (!Validations.validarCorreo(txtCorreo.getText())) {
        JlbCorreo.setText("Error: Ingrese correo Válido");
        return;
    }

    if (!Validations.validarTelefono(txtTelefono.getText())) {
        JlbTelefono.setText("Error: Número de teléfono inválido");
        return;
    }

    if (!Validations.validarCedula(txtCi1.getText())) {
        JlbCedula1.setText("Error: Ingrese una cédula válida de 10 dígitos");
        return;
    }

    int edad = (int) JSedad.getValue();
    if (!Validations.validarEdad(edad)) {
        Jlbedad.setText("Error: Ingrese una edad válida entre 1 y 150 años");
        return;
    }
    
    mongo.insertarUsuario();
    mongo.cerrarConexion();
    
    }//GEN-LAST:event_JLOpRegistrarMouseClicked
   
    
    private void JLOpRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpRegistrarMouseEntered
        JLRegistrar.setFont(new Font("Calibri", Font.BOLD, 18));
        // TODO add your handling code here:
    }//GEN-LAST:event_JLOpRegistrarMouseEntered

    private void JLOpRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLOpRegistrarMouseExited
        JLRegistrar.setFont(new Font("Calibri", Font.PLAIN, 18));// TODO add your handling code here:
    }//GEN-LAST:event_JLOpRegistrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel JLOpRegistrar;
    private javax.swing.JLabel JLOpVolver;
    private javax.swing.JLabel JLRegistrar;
    private javax.swing.JLabel JLVolver;
    public javax.swing.JSpinner JSedad;
    private javax.swing.JLabel JlbCedula1;
    private javax.swing.JLabel JlbContraseña;
    private javax.swing.JLabel JlbCorreo;
    public javax.swing.JLabel JlbNombreUsuario;
    private javax.swing.JLabel JlbTelefono;
    private javax.swing.JLabel Jlbedad;
    public javax.swing.JTextField txtCi1;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JPasswordField txtcont;
    public javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
